<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.0.0" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.7" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.7" />
      <PackageReference Include="Scalar.AspNetCore" Version="2.6.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HealthBeside.Domain\HealthBeside.Domain.csproj" />
      <ProjectReference Include="..\HealthBeside.Infrastructure\HealthBeside.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Query\" />
    </ItemGroup>

</Project>
